// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
        user_id,
        name,
        type,
        balance,
        currency,
        description,
        is_active
    )
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, TRUE))
RETURNING id, user_id, name, type, balance, currency, description, is_active, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Balance     pgtype.Numeric `json:"balance"`
	Currency    string         `json:"currency"`
	Description pgtype.Text    `json:"description"`
	Column7     interface{}    `json:"column_7"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Balance,
		arg.Currency,
		arg.Description,
		arg.Column7,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, type, balance, currency, description, is_active, created_at, updated_at, deleted_at
FROM accounts
WHERE id = $1
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, type, balance, currency, description, is_active, created_at, updated_at, deleted_at
FROM accounts
WHERE user_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.Currency,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE accounts
SET deleted_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, id)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = COALESCE($2, name),
    type = COALESCE($3, type),
    balance = COALESCE($4, balance),
    currency = COALESCE($5, currency),
    description = COALESCE($6, description),
    is_active = COALESCE($7, is_active),
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, user_id, name, type, balance, currency, description, is_active, created_at, updated_at, deleted_at
`

type UpdateAccountParams struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Balance     pgtype.Numeric `json:"balance"`
	Currency    string         `json:"currency"`
	Description pgtype.Text    `json:"description"`
	IsActive    pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Balance,
		arg.Currency,
		arg.Description,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, user_id, name, type, balance, currency, description, is_active, created_at, updated_at, deleted_at
`

type UpdateAccountBalanceParams struct {
	ID      pgtype.UUID    `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
