// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, description, color, icon)
VALUES($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, color, icon, is_active, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       string      `json:"color"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletedCategory = `-- name: DeletedCategory :exec
UPDATE categories
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeletedCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletedCategory, id)
	return err
}

const getCategoriesByUserID = `-- name: GetCategoriesByUserID :many
SELECT id, user_id, name, description, color, icon, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE user_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetCategoriesByUserID(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, description, color, icon, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByUserIDAndName = `-- name: GetCategoryByUserIDAndName :one
SELECT id, user_id, name, description, color, icon, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE user_id = $1
    AND name = $2
    AND deleted_at is NULL
`

type GetCategoryByUserIDAndNameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) GetCategoryByUserIDAndName(ctx context.Context, arg GetCategoryByUserIDAndNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByUserIDAndName, arg.UserID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = COALESCE($2, description),
    description = COALESCE($3, description),
    color = COALESCE($4, color),
    icon = COALESCE($5, icon),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, user_id, name, description, color, icon, is_active, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       pgtype.Text `json:"color"`
	Icon        pgtype.Text `json:"icon"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Icon,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
