// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error)
	ListTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error)
	ListTransactionsByPeriod(ctx context.Context, arg ListTransactionsByPeriodParams) ([]Transaction, error)
	ListTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]Transaction, error)
	ListUsers(ctx context.Context) ([]User, error)
	SoftDeleteAccount(ctx context.Context, id pgtype.UUID) error
	SoftDeleteTransaction(ctx context.Context, id pgtype.UUID) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
