// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (user_id, type, title, description, start_date, end_date, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, type, title, description, start_date, end_date, data, created_at, updated_at
`

type CreateReportParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	Data        []byte             `json:"data"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Data,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, user_id, type, title, description, start_date, end_date, data, created_at, updated_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportsByUser = `-- name: ListReportsByUser :many
SELECT id, user_id, type, title, description, start_date, end_date, data, created_at, updated_at
FROM reports
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsByUser(ctx context.Context, userID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :one
UPDATE reports
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    data = COALESCE($4, data),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, type, title, description, start_date, end_date, data, created_at, updated_at
`

type UpdateReportParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Data        []byte      `json:"data"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReport,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Data,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
