// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
        user_id,
        account_id,
        category_id,
        type,
        amount,
        description,
        status,
        date
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        COALESCE($7, 'completed'),
        $8
    )
RETURNING id, user_id, account_id, category_id, type, amount, description, status, date, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Type        string             `json:"type"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description string             `json:"description"`
	Column7     interface{}        `json:"column_7"`
	Date        pgtype.Timestamptz `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Column7,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, account_id, category_id, type, amount, description, status, date, created_at, updated_at, deleted_at
FROM transactions
WHERE id = $1
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, user_id, account_id, category_id, type, amount, description, status, date, created_at, updated_at, deleted_at
FROM transactions
WHERE account_id = $1
    AND deleted_at IS NULL
ORDER BY date DESC,
    created_at DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByPeriod = `-- name: ListTransactionsByPeriod :many
SELECT id, user_id, account_id, category_id, type, amount, description, status, date, created_at, updated_at, deleted_at
FROM transactions
WHERE user_id = $1
    AND date >= $2
    AND date < $3
    AND deleted_at IS NULL
ORDER BY date DESC,
    created_at DESC
`

type ListTransactionsByPeriodParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Date   pgtype.Timestamptz `json:"date"`
	Date_2 pgtype.Timestamptz `json:"date_2"`
}

func (q *Queries) ListTransactionsByPeriod(ctx context.Context, arg ListTransactionsByPeriodParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByPeriod, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, account_id, category_id, type, amount, description, status, date, created_at, updated_at, deleted_at
FROM transactions
WHERE user_id = $1
    AND deleted_at IS NULL
ORDER BY date DESC,
    created_at DESC
`

func (q *Queries) ListTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET deleted_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, id)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = COALESCE($1, account_id),
    category_id = COALESCE($2, category_id),
    type = COALESCE($3, type),
    amount = COALESCE($4, amount),
    description = COALESCE($5, description),
    status = COALESCE($6, status),
    date = COALESCE($7, date),
    updated_at = NOW()
WHERE id = $8
    AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, type, amount, description, status, date, created_at, updated_at, deleted_at
`

type UpdateTransactionParams struct {
	AccountID   pgtype.UUID        `json:"account_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Type        pgtype.Text        `json:"type"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	Date        pgtype.Timestamptz `json:"date"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Status,
		arg.Date,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
